### PR TITLE
make all geometries valid; closes #16

### LINKED ISSUE #16: geometry evaluation error
Error generated when matching to 2000 census tracts"

`finding containing geography for each point...`
`Error in CPL_geos_op2(op, x, y) :
  Evaluation error: TopologyException: Input geom 1 is invalid: Ring Self-intersection at or near point 1050692.1045394999 1916457.7976013292 at 1050692.1045394999 1916457.7976013292.`
`Calls: <Anonymous> ... geos_op2_df -> geos_op2_geom -> st_sfc -> CPL_geos_op2`
`Execution halted`

The first (lat, lon) in the file is (39.226238, -84.555914)

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
Andrew's example coordinates (39.625348, -83.542276) cause the geometry error in GHA.

**Review by cole-brokamp — CHANGES_REQUESTED** [review]
do we know exactly why this bug was happening?  is that coordinate right on a boundary or something?

Can you please add the "st_make_valid" step to the README on the geomarker data details?

Do you think we should also save these valid files to `s3://geomarker/geometries` too?  (like you did for `s3:///geomarker/geometries/census_tracts_1970_to_2020.rds` and `s3:///geomarker/geometries/census_tracts_1970_to_2020_valid.rds`?)

**Comment by erikarasnick** [comment]
The polygon does not appear different when plotted with `mapview` before and after `st_make_valid`, but I think it has to do with the polygon having that "loop". 

Screen Shot 2022-01-31 at 3 49 03 PM

I overwrote the rds files in s3... so they are the valid polygons but I didn't change the names of the files.

File: 00_make_block_group_shp.R [hunk 1]
```diff
@@ -67,5 +82,9 @@ tracts_sf_1970 <- tracts_sf_1970 %>%
 
 saveRDS(tracts_sf_1970, "tracts_1970_5072.rds")
 
+tracts_sf_1970 <- s3::s3_get("s3://geomarker/geometries/tracts_1970_5072.rds") %>% readRDS()
+tracts_sf_1970 <- sf::st_make_valid(tracts_sf_1970)
+saveRDS(tracts_sf_1970, "tracts_1970_5072.rds")
```
Comment (cole-brokamp) [inline 00_make_block_group_shp.R]: you don't need to get files from s3, right?  they are read in locally from the shp files...

I'm assuming this is how you updated the files to make them valid? But we should code in how it would be done "from scratch":

- make the `st_read` filepaths relative to the working directory, so we don't have to include your username/Downloads... etc
- put comment in R code where you uploaded the rds files to S3

**Review by cole-brokamp — CHANGES_REQUESTED** [review]

File: 00_make_block_group_shp.R (hunk 1 above)
Comment (erikarasnick) [reply 00_make_block_group_shp.R]: That makes sense. Sometimes I'm not sure if I should keep code exactly how I did it or clean it up, but I don't think there should be any conflicts here with the cleaned up workflow.

**Review by cole-brokamp — APPROVED** [review]
